version: '3'

services:
  mysql:
    container_name: mercafacil-api-mysql
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=admin
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_HOST=%
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker-volumes/mercafacil-api/mysql:/data/dbc

  postgresql:
    container_name: mercafacil-api-postgres
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_USER: 'admin'
    volumes:
      - ./docker-volumes/mercafacil-api/postgres:/data/dbc
